name: Test greeting action

on:
  pull_request:
  workflow_dispatch:
    
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      working-directory: ./greeting-action
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install
      - run: npm run build
      - run: rm -rf node_modules
      - uses: ./greeting-action
      - uses: ./greeting-action
        with:
          person: Batman
